name: update
on: pull_request

jobs:
  update:
   name: EAS Update
   runs-on: ubuntu-latest
   steps:
     - name: Check for EXPO_TOKEN
       run: |
         if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
           echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
           exit 1
         fi
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: 16.x
         cache: npm
     - uses: expo/expo-github-action@v7
       with:
         expo-version: latest
         eas-version: latest
         token: ${{ secrets.EXPO_TOKEN }}
     - name: Install dependencies
       run: npm install
     - name: Publish update
       run: eas update --auto

     - name: Publish update
       run: eas update --branch preview --auto
